name: Render and Display Bookdown

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    container: rocker/verse
    steps:
      - name: Build Bookdown
        run: echo "$(ls)"
        #run: Rscript -e "bookdown::render_book('index.Rmd', output_dir = 'public')"
